//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UlrikHovsgaardAlgorithmTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UlrikHovsgaardAlgorithmTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dcrgraph&gt;
        ///&lt;specification&gt;
        ///&lt;resources&gt;
        ///&lt;events&gt;
        ///&lt;event id=&quot;A&quot; scope=&quot;private&quot; &gt;
        ///                    &lt;custom&gt;
        ///                        &lt;visualization&gt;
        ///                            &lt;location /&gt;
        ///                        &lt;/visualization&gt;
        ///                        &lt;roles&gt;
        ///                            &lt;role&gt;&lt;/role&gt;
        ///                        &lt;/roles&gt;
        ///                        &lt;groups&gt;
        ///                            &lt;group /&gt;
        ///                        &lt;/groups&gt;
        ///                        &lt;eventType&gt;&lt;/eventType&gt;
        ///                      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllInclusion9ActivitiesGraph {
            get {
                return ResourceManager.GetString("AllInclusion9ActivitiesGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dcrgraph&gt;
        ///&lt;specification&gt;
        ///&lt;resources&gt;
        ///&lt;events&gt;
        ///&lt;event id=&quot;Collect Documents&quot; scope=&quot;private&quot; &gt;
        ///                    &lt;custom&gt;
        ///                        &lt;visualization&gt;
        ///                            &lt;location /&gt;
        ///                        &lt;/visualization&gt;
        ///                        &lt;roles&gt;
        ///                            &lt;role&gt;&lt;/role&gt;
        ///                        &lt;/roles&gt;
        ///                        &lt;groups&gt;
        ///                            &lt;group /&gt;
        ///                        &lt;/groups&gt;
        ///                        &lt;eventType&gt;&lt;/event [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mortgageGRAPH {
            get {
                return ResourceManager.GetString("mortgageGRAPH", resourceCulture);
            }
        }
    }
}
