//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UlrikHovsgaardAlgorithm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UlrikHovsgaardAlgorithm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;!-- This file has been generated with the OpenXES library. It conforms --&gt;
        ///&lt;!-- to the XML serialization of the XES standard for log storage and --&gt;
        ///&lt;!-- management. --&gt;
        ///&lt;!-- XES standard version: 1.0 --&gt;
        ///&lt;!-- OpenXES library version: 1.0RC7 --&gt;
        ///&lt;!-- OpenXES is available from http://www.openxes.org/ --&gt;
        ///&lt;log xes.version=&quot;1.0&quot; xes.features=&quot;nested-attributes&quot; openxes.version=&quot;1.0RC7&quot; xmlns=&quot;http://www.xes-standard.org/&quot;&gt;
        ///	&lt;extension name=&quot;Organizational&quot; prefi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BPIC15_1_xes {
            get {
                return ResourceManager.GetString("BPIC15_1_xes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dcrgraph title=&quot;DCR&quot; dataTypesStatus=&quot;hide&quot; filterLevel=&quot;-1&quot; zoomLevel=&quot;0&quot;&gt;
        ///    &lt;specification&gt;
        ///        &lt;resources&gt;
        ///            &lt;events&gt;
        ///                &lt;event id=&quot;A&quot; scope=&quot;private&quot; &gt;
        ///                    &lt;custom&gt;
        ///                        &lt;visualization&gt;
        ///                            &lt;location xLoc=&quot;874&quot; yLoc=&quot;213&quot; /&gt;
        ///                        &lt;/visualization&gt;
        ///                        &lt;roles&gt;
        ///                            &lt;role&gt;&lt;/role&gt;
        ///                        &lt;/roles&gt;
        ///                        &lt;groups&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DCRGraphNETtest {
            get {
                return ResourceManager.GetString("DCRGraphNETtest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;!-- This file has been generated with the OpenXES library. It conforms --&gt;
        ///&lt;!-- to the XML serialization of the XES standard for log storage and --&gt;
        ///&lt;!-- management. --&gt;
        ///&lt;!-- XES standard version: 1.0 --&gt;
        ///&lt;!-- OpenXES library version: 1.0RC7 --&gt;
        ///&lt;!-- OpenXES is available from http://www.openxes.org/ --&gt;
        ///&lt;log xes.version=&quot;1.0&quot; xes.features=&quot;nested-attributes&quot; openxes.version=&quot;1.0RC7&quot; xmlns=&quot;http://www.xes-standard.org/&quot;&gt;
        ///	&lt;extension name=&quot;Lifecycle&quot; prefix=&quot;li [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Hospital_log {
            get {
                return ResourceManager.GetString("Hospital_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;!-- This file has been generated with the OpenXES library. It conforms --&gt;
        ///&lt;!-- to the XML serialization of the XES standard for log storage and --&gt;
        ///&lt;!-- management. --&gt;
        ///&lt;!-- XES standard version: 1.0 --&gt;
        ///&lt;!-- OpenXES library version: 1.0RC7 --&gt;
        ///&lt;!-- OpenXES is available from http://www.openxes.org/ --&gt;
        ///&lt;log xes.version=&quot;1.0&quot; xes.features=&quot;nested-attributes&quot; openxes.version=&quot;1.0RC7&quot; xmlns=&quot;http://www.xes-standard.org/&quot;&gt;
        ///	&lt;trace&gt;
        ///		&lt;date key=&quot;endDate&quot; value=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TwoTracesTest {
            get {
                return ResourceManager.GetString("TwoTracesTest", resourceCulture);
            }
        }
    }
}
